name: PHP CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t rahulhub1313/mini-cicd-php .

      - name: Run container to validate
        run: |
          docker run -d --name php-container -p 8080:80 rahulhub1313/mini-cicd-php
          sleep 5
          curl -s http://localhost:8080 | grep "Hello from PHP"

      - name: Push Docker image
        run: docker push rahulhub1313/mini-cicd-php

      - name: Cleanup container
        run: |
          docker stop php-container
          docker rm php-container

