name: PHP CI/CD (Self-Hosted)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t rahulhub1313/mini-cicd-php .

      - name: Stop existing container if running
        run: |
          docker stop php-container || true
          docker rm php-container || true

      - name: Run live container
        run: |
          docker run -d --name php-container -p 8080:80 rahulhub1313/mini-cicd-php
          echo "Container is now running on http://localhost:8080"

      - name: Push Docker image to Docker Hub
        run: docker push rahulhub1313/mini-cicd-php
