name: Cleanup After Audit

on:
  workflow_run:
    workflows: ["Deploy After Build"]
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Cleanup Stage
        run: echo "🧹 Final Cleanup after audit complete"
