name: Deploy After Build

on:
  workflow_run:
    workflows: ["Audit After Notify"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Code
        run: echo "Deploying   app..."
